parameters:
  braintree.factory.class: EcommerceBundle\Factory\BraintreeFactory
  paypal.factory.class: EcommerceBundle\Factory\PayPalFactory
  redsys.factory.class: EcommerceBundle\Factory\RedsysFactory

services:
    
    ecommerce_extension:
        class: EcommerceBundle\Twig\EcommerceExtension
        arguments:
            - { parameters: %core% }
        calls:
            - [setContainer, [@service_container] ]
        tags:
            - { name: twig.extension }
            
    ecommerce_extension_string:
        class: Twig_Extension_StringLoader
        tags:
            - { name: 'twig.extension' }
                    
    braintree_factory:
        class:  "%braintree.factory.class%"
        arguments: ["%braintree.environment%", "%braintree.merchant_id%", "%braintree.public_key%", "%braintree.private_key%"]
    
    paypal_factory:
        class:  "%paypal.factory.class%"
        arguments: ["%paypal.host%", "%paypal.client_id%", "%paypal.secret%", "%paypal.return_url%", "%paypal.cancel_url%"]
            
    payment_manager:
        class: EcommerceBundle\Service\PaymentManager
        calls:
            - [setContainer, [@service_container] ]
            
    checkout_manager:
        class: EcommerceBundle\Service\CheckoutManager
        arguments:
            - { parameters: %core% }
            - @session
            - @doctrine.orm.entity_manager
            - @cart_provider
            - @security.token_storage
            - @router
            - @kernel
            - @core.mailer
            - @braintree_factory
            - @paypal_factory
            - "%ecommerce.advert_unit_price%"
            - "%ecommerce.special_percentage_charge%"
            - "%ecommerce.delivery_expenses_type%"
            - "%ecommerce.delivery_expenses_percentage%"
            - "%ecommerce.vat%"
            - "@form.factory"
            - "@validator"
            
    cart_provider:
        class: EcommerceBundle\Service\CartProvider
        arguments:
            - @cart_storage
            - @doctrine.orm.entity_manager
  
    cart_storage:
        class: EcommerceBundle\Service\CartStorage
        arguments:
            - @session
 
     