parameters:
  braintree.factory.class: EcommerceBundle\Factory\BraintreeFactory

services:
    braintree_factory:
        class:  "%braintree.factory.class%"
        arguments: ["%braintree.environment%", "%braintree.merchant_id%", "%braintree.public_key%", "%braintree.private_key%"]

    ecommerce_extension:
        class: EcommerceBundle\Twig\EcommerceExtension
        arguments:
            - { parameters: %core% }
        calls:
            - [setContainer, [@service_container] ]
        tags:
            - { name: twig.extension }
            
    checkout_manager:
        class: EcommerceBundle\Service\CheckoutManager
        arguments:
            - { parameters: %core% }
            - @session
            - @doctrine.orm.entity_manager
            - @cart_provider
            - @security.token_storage
            - @router
            - @kernel
            - @core.mailer
            - @braintree_factory

    cart_provider:
        class: EcommerceBundle\Service\CartProvider
        arguments:
            - @cart_storage
            - @doctrine.orm.entity_manager
  
    cart_storage:
        class: EcommerceBundle\Service\CartStorage
        arguments:
            - @session
 
     